WRanalysis: python.combineTools Namespace Reference
python.combineTools Namespace Reference
Functions
def makeDataCardSingleBin
creates a datacard for combine for signal and background
def getEEJJMassHisto
gets fourObjectMass histogram from tree in root file
def getMuMuJJMassHisto
def getSignalMassHisto
def getTTBarNEvents
def getDYNEvents
def getNEvents
def runCombine
calls and parses command for `combine'
Variables
list datafolder = environ['LOCALRT']
dictionary mass_cut = {mass:(low,hi) for mass,low,hi in [ map(int,s.split()) for s in open("configs/mass_cuts.txt",'r').read().split('\n') if s and s[0] != "#"]}
list ID = sys.argv[1]
string command = " "
tuple result = runCombine(command)
Function Documentation
def python.combineTools.getDYNEvents (MWR, channel, lumi)
Referenced by python.combineTools.getNEvents().
def python.combineTools.getEEJJMassHisto (MWR, binsize = 100)
gets fourObjectMass histogram from tree in root file
Parameters
MWR Mass of WR
binsize
Returns
TH1F of fourobjectmass
Referenced by python.combineTools.getSignalMassHisto().
def python.combineTools.getMuMuJJMassHisto (MWR, binsize = 100)
Referenced by python.combineTools.getSignalMassHisto().
def python.combineTools.getNEvents (MWR, channel, process, lumi)
References python.combineTools.getDYNEvents(), python.combineTools.getSignalMassHisto(), and python.combineTools.getTTBarNEvents().
def python.combineTools.getSignalMassHisto (MWR, channel, binsize = 100)
References python.combineTools.getEEJJMassHisto(), and python.combineTools.getMuMuJJMassHisto().
Referenced by python.combineTools.getNEvents().
def python.combineTools.getTTBarNEvents (MWR, channel, lumi)
Referenced by python.combineTools.getNEvents().
def python.combineTools.makeDataCardSingleBin (outfile, bin_name, nObs, signal_tuple, background_tuples, systematics = [])
creates a datacard for combine for signal and background
Parameters
outfile String of filename
bin_name Name for bin
nObs number of observed
signal_tuple (sig_name, signal_rate)
background_tuples list of (name, rate) for backgrounds
Returns
signal_rate, tuple of bg rates
def python.combineTools.runCombine (command)
calls and parses command for `combine'
Parameters
command a list to pass to subprocess.check_output
Returns
(mean, meanError), (onesig_minus,onesig_plus), (twosig_minus,twosig_plus)
Variable Documentation
string python.combineTools.command = " "
list python.combineTools.datafolder = environ['LOCALRT']
list python.combineTools.ID = sys.argv[1]
dictionary python.combineTools.mass_cut = {mass:(low,hi) for mass,low,hi in [ map(int,s.split()) for s in open("configs/mass_cuts.txt",'r').read().split('\n') if s and s[0] != "#"]}
tuple python.combineTools.result = runCombine(command)