WRanalysis: python.PlotUtils Namespace Reference
python.PlotUtils Namespace Reference
Functions
def customROOTstyle
def customPalette
def drawMultipleGrid
def saveHists
def drawHist
def drawMultipleSame
Function Documentation
def python.PlotUtils.customPalette (zeropoint = 0.5)
def python.PlotUtils.customROOTstyle ()
Referenced by python.PlotUtils.drawHist(), python.PlotUtils.drawMultipleSame(), and python.PlotUtils.saveHists().
def python.PlotUtils.drawHist (hist, name, width = 500, height = 500, drawoptions = "")
References python.PlotUtils.customROOTstyle().
Referenced by python.PlotUtils.saveHists().
def python.PlotUtils.drawMultipleGrid (hists, outname, limits = [], setLogY = False, setLogZ = False, ncols = 3, width = 1500, height = 1100)
def python.PlotUtils.drawMultipleSame (hists, labels, filename, colors = [], width = 500, height = 500, norm = False, xtitle = "", ytitle = "", rebin = 0, leg = "top", logy = False)
References python.PlotUtils.customROOTstyle().
def python.PlotUtils.saveHists (file, prefix = "", filter = "")
References python.PlotUtils.customROOTstyle(), and python.PlotUtils.drawHist().